### ISSUE TITLE
Body text hidden

### ISSUE THREAD

**Issue by danielfdsilva** [developmentseed/ui-seed#41]
Prevent  body text from getting behind footer

As seen on RAM docs
![image](https://user-images.githubusercontent.com/1090606/31991346-76b5a5b2-b96f-11e7-959b-068ade8b4508.png)

**Comment by ricardomestre** [comment]
@danielfdsilva Wrong repo? Should this be on Doc Seed?

**Comment by danielfdsilva** [comment]
@ricardomestre ups. moved https://github.com/developmentseed/doc-seed/issues/35
